name: 'AutoCoder'
description: 'Generates code from GitHub issues using ChatGPT and creates a pull request automatically.'
author: 'Samuel Zuniga'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token used for authentication and pull request creation'
    required: true
  REPOSITORY:
    description: 'Repository where the action is executed'
    required: true
  ISSUE_NUMBER:
    description: 'The issue number that triggered the action'
    required: true
  OPENAI_API_KEY:
    description: 'OpenAI API key for ChatGPT code generation'
    required: true
  SCRIPT_PATH:
    description: 'Path to the script that interacts with ChatGPT'
    required: true
    default: 'scripts/script.sh'
  LABEL:
    description: 'Label that triggers this action'
    required: true
    default: 'autocoder-bot'

outputs:
  pull_request_url:
    description: 'URL of the pull request created with generated code'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4



    - name: Make script executable
      run: chmod +x ${{ inputs.SCRIPT_PATH }}

    - name: Run AutoCoder script
      run: |
        ${{ inputs.SCRIPT_PATH }} \
          "${{ inputs.GITHUB_TOKEN }}" \
          "${{ inputs.REPOSITORY }}" \
          "${{ inputs.ISSUE_NUMBER }}" \
          "${{ inputs.OPENAI_API_KEY }}"

    - name: Commit generated files
      run: |
        git add .
        git diff --cached --quiet || git commit -m "Auto-generated code for issue #${{ inputs.ISSUE_NUMBER }}"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        branch: autocoder-branch-${{ inputs.ISSUE_NUMBER }}
        base: main
        title: "AutoCoder: generated code for issue #${{ inputs.ISSUE_NUMBER }}"
        labels: ${{ inputs.LABEL }}
        body: "This pull request contains code generated automatically by the AutoCoder action."
